module.exports = [
    {
      type: 'autogenerated',
      dirName: '.', // Genera el resto de los posts automáticamente
    },
  {
    type: 'link',
    label: 'Authors',
    href: '/blog/authors',
  },
];
